In [4]:
import numpy as np
np.random.seed(30)

# Defining inputs(X) with their labels(y)
x = np.random.rand(3,3)
y = np.array([0,1,1])
y = y.reshape(1,3)
m = y.size #Number of training examples

# Initializing weights, bias for hidden layer
w1 = np.random.randn(4,3) * 0.01
print('Hidden layer weights before:')
print(w1)
b1 = np.zeros((4,1))

# Initializing weights, bias  for output layer
w2 = np.random.randn(1,4) * 0.01
print('Output layer weights before:')
print(w2)
b2 = 0

# Set learning rate and number of iterations
lr = 0.5
iterations = 60

for i in range(iterations):
    # Function to predict (Not in binary form), hidden layer
    z1 = np.dot(w1, x) + b1 
    
    # Predicted y hat (applying the tanh activation function), hidden layer
    a1 = (np.exp(z1)-np.exp(-z1)) / (np.exp(z1)+np.exp(-z1))
    
    da1 = 1 - np.square((np.tanh(z1))) # derivative of tanh activation function

    # 2nd layer with sigmoid activation function
    z2 = np.dot(w2, a1) + b2
    a2 = 1 / (1 + np.exp(-z2))
    
    da2 = (a2 * (1-a2))
    print('Predicted labels:' + str(np.round(a2)), 'Actual labels:' + str(y))
    
    # Calculating the loss
    loss = -(y * np.log10(a2) + (1-y) * np.log10(1-a2))

    # Calculating the cost function
    cost = (np.sum(loss))/(m)
    print('cost', cost)

    # Gradient descent
    dz2 = np.subtract(a2, y) #dz2 = ((-y/a2) + ((1-y)/(1-a2))) * (da2) alternative way of getting dz2
    
    dw2 = np.dot(dz2, a1.T)/(m)
    
    db2 = (np.sum(dz2, axis=1, keepdims = True))/m
    
    dz1 = (np.dot(w2.T,dz2)) * (da1)
    
    dw1 = np.dot(dz1, x.T)/(m)
    
    db1 = (np.sum(dz1, axis=1, keepdims = True))/m

    # Updating weights and bias
    w1 = w1 - np.dot(lr, dw1)
    b1 = b1 - np.dot(lr, db1)
    w2 = w2 - np.dot(lr, dw2)
    b2 = b2 - np.dot(lr, db2)
    
print('Hidden layer Weight after logistic regression:')
print(w1)
print('Output layer Weight after logistic regression:')
print(w2)
print('Hidden layer Bias after logistic regression:',)
print(b1)
print('Output layer Bias after logistic regression:',)
print(b2)

Hidden layer weights before:
[[-0.01036466 -0.00265865  0.01167249]
 [ 0.02834345  0.0065195  -0.0131811 ]
 [ 0.00890789  0.01111226  0.00455793]
 [-0.01750345 -0.00285416 -0.00074511]]
Output layer weights before:
[[ 0.01266575 -0.0002214   0.00263722 -0.02280468]]
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.3010190638832428
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.2953546401878497
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.2910163282912544
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.2876894179304417
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.2851333212392633
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.28316491721063414
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.28164507028527114
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.2804680578073599
Predicted labels:[[1. 1. 1.]] Actual labels:[[0 1 1]]
cost 0.27955343712270264
Predicted labels:[[1. 1. 1.]